import Image from "next/image"
import {
  AlertTriangle,
  ArrowRight,
  BellIcon,
  BookImageIcon,
  BookOpenText,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleCheck,
  CircleIcon,
  ClockIcon,
  CopyIcon,
  CreditCard,
  DatabaseZapIcon,
  ExternalLinkIcon,
  File,
  FileText,
  FlagIcon,
  FolderPlus,
  GlobeIcon,
  HeartIcon,
  HelpCircle,
  Image as ImageIcon,
  Laptop,
  LineChartIcon,
  Loader2,
  LockIcon,
  LucideIcon,
  MailIcon,
  Monitor,
  Moon,
  MoreVertical,
  PencilIcon,
  PhoneIcon,
  Pizza,
  Plus,
  PuzzleIcon,
  Search,
  Settings,
  ShieldIcon,
  ShoppingCartIcon,
  StarIcon,
  SunMedium,
  TagIcon,
  ToggleRightIcon,
  Trash,
  Unlink,
  UserCogIcon,
  UserIcon,
  X,
  ZapIcon,
} from "lucide-react"
import {
  FaDiscord,
  FaFacebook,
  FaGithub,
  FaGoogle,
  FaInstagram,
  FaTiktok,
} from "react-icons/fa"
import { FaXTwitter } from "react-icons/fa6"
import {
  MdOutlineDescription,
  MdOutlineIntegrationInstructions,
  MdOutlineMemory,
} from "react-icons/md"
import { SiPrisma } from "react-icons/si"

export type Icon = LucideIcon

function LogoIcon({ className }: { className?: string }) {
  return (
    <Image
      src="/favicons/android-chrome-192x192.png"
      alt="logo"
      className={className}
      width={32}
      height={32}
    />
  )
}

export const Icons = {
  logo: LogoIcon,
  logoLucide: LogoIcon,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: ImageIcon,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: UserIcon,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  search: Search,
  twitter: FaXTwitter,
  check: Check,
  orderbook: BookOpenText,
  chevronsUpDown: ChevronsUpDown,
  phone: PhoneIcon,
  mail: MailIcon,
  pencil: PencilIcon,
  student: PencilIcon,
  teacher: UserCogIcon,
  monitor: Monitor,
  discord: FaDiscord,
  github: FaGithub,
  memory: MdOutlineMemory,
  integrationInstructions: MdOutlineIntegrationInstructions,
  description: MdOutlineDescription,
  bell: BellIcon,
  heart: HeartIcon,
  cart: ShoppingCartIcon,
  shield: ShieldIcon,
  folderPlus: FolderPlus,
  copy: CopyIcon,
  external: ExternalLinkIcon,
  unlink: Unlink,
  clock: ClockIcon,
  tag: TagIcon,
  flag: FlagIcon,
  star: StarIcon,
  circleCheck: CircleCheck,
  lock: LockIcon,
  graph: LineChartIcon,
  puzzle: PuzzleIcon,
  databaseZap: DatabaseZapIcon,
  prisma: SiPrisma,
  globe: GlobeIcon,
  blog: BookImageIcon,
  zap: ZapIcon,
  toggleRight: ToggleRightIcon,
  facebook: FaFacebook,
  google: FaGoogle,
  circle: CircleIcon,
  tiktok: FaTiktok,
  instagram: FaInstagram,
}
