import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().min(1),
    DATABASE_PASSWORD: z.string().min(1),
    SUPABSE_URL: z.string().min(1),
    SUPABASE_JWT_SECRET: z.string().min(1),
    SUPABSE_ANON_API: z.string().min(1),
    SUPABSE_SERVICE_ROLE: z.string().min(1),
    LOGSNOG_API_TOKEN: z.string().min(1),
    LOGSNOG_PROJECT_NAME: z.string().min(1),
    FROM_EMAIL: z.string().min(1),
    FROM_EMAIL_PASSWORD: z.string().min(1),
    SMTP_SERVER: z.string().min(1),
    FROM_EMAIL_GMAIL: z.string().min(1),
    SMTP_PORT: z.string().min(1),
    NEXT_PUBLIC_APP_URL: z.string().min(1),
    NEXTAUTH_URL: z.string().min(1),
    NEXTAUTH_SECRET: z.string().min(1),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
    SUPABSE_URL: process.env.SUPABSE_URL,
    SUPABASE_JWT_SECRET: process.env.SUPABASE_JWT_SECRET,
    SUPABSE_ANON_API: process.env.SUPABSE_ANON_API,
    SUPABSE_SERVICE_ROLE: process.env.SUPABSE_SERVICE_ROLE,
    LOGSNOG_API_TOKEN: process.env.LOGSNOG_API_TOKEN,
    LOGSNOG_PROJECT_NAME: process.env.LOGSNOG_PROJECT_NAME,
    FROM_EMAIL: process.env.FROM_EMAIL,
    FROM_EMAIL_GMAIL: process.env.FROM_EMAIL_GMAIL,
    SMTP_PORT: process.env.SMTP_PORT,
    FROM_EMAIL_PASSWORD: process.env.FROM_EMAIL_PASSWORD,
    SMTP_SERVER: process.env.SMTP_SERVER,
    SMTP_PORT: process.env.SMTP_PORT,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  },
})
